import '@/app/styles/app.css';
import ThemeRegistry from '@/components/theme-registry/theme.registry';
import AuthProvider from './lib/auth.provider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <AuthProvider>
          <body>{children}</body>
        </AuthProvider>
      </ThemeRegistry>
    </html>
  );
}
