import '@/app/styles/app.css';
import ThemeRegistry from '@/components/theme-registry/theme.registry';
import { ToastProvider } from '@/utils/toast';
import AuthProvider from './lib/auth.provider';
import { TrackContextProvider } from './lib/track.wrapper';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <AuthProvider>
          <ToastProvider>
            <TrackContextProvider>
              <body>{children}</body>
            </TrackContextProvider>
          </ToastProvider>
        </AuthProvider>
      </ThemeRegistry>
    </html>
  );
}
